package ujfe.live;

public final class LiveClientScript {
    private static final String SCRIPT = ""
            + "(function(){\n"
            + "  function readLocalStorage() {\n"
            + "    var values = {};\n"
            + "    try {\n"
            + "      for (var index = 0; index < window.localStorage.length; index++) {\n"
            + "        var key = window.localStorage.key(index);\n"
            + "        if (key) { values[key] = window.localStorage.getItem(key); }\n"
            + "      }\n"
            + "    } catch (error) {\n"
            + "      console.warn('UJFE could not read localStorage', error);\n"
            + "    }\n"
            + "    return values;\n"
            + "  }\n"
            + "  function clientState() {\n"
            + "    return { cookies: document.cookie || '', localStorage: readLocalStorage() };\n"
            + "  }\n"
            + "  function replaceRoot(html) {\n"
            + "    var root = document.getElementById('ujfe-root');\n"
            + "    if (root) { root.innerHTML = html; }\n"
            + "  }\n"
            + "  function replaceCss(css) {\n"
            + "    var style = document.querySelector('style[data-ujfe-css]');\n"
            + "    if (style && typeof css === 'string') { style.textContent = css; }\n"
            + "  }\n"
            + "  function applyLiveResponse(body) {\n"
            + "    try {\n"
            + "      var payload = JSON.parse(body);\n"
            + "      if (payload && typeof payload.html === 'string') {\n"
            + "        replaceCss(payload.css || '');\n"
            + "        replaceRoot(payload.html);\n"
            + "        return;\n"
            + "      }\n"
            + "    } catch (error) {\n"
            + "      // Older endpoints can still return a plain HTML fragment.\n"
            + "    }\n"
            + "    replaceRoot(body);\n"
            + "  }\n"
            + "  function postLive(url, payload) {\n"
            + "    return fetch(url, {\n"
            + "      method: 'POST',\n"
            + "      headers: { 'Content-Type': 'application/json' },\n"
            + "      body: JSON.stringify(payload)\n"
            + "    })\n"
            + "      .then(function(response) {\n"
            + "        if (!response.ok) { throw new Error('UJFE request failed'); }\n"
            + "        return response.text();\n"
            + "      })\n"
            + "      .then(applyLiveResponse)\n"
            + "      .catch(function(error) { console.error(error); });\n"
            + "  }\n"
            + "  document.addEventListener('DOMContentLoaded', function() {\n"
            + "    postLive('/_ujfe/state', { clientState: clientState() });\n"
            + "  });\n"
            + "  function postEvent(eventId) {\n"
            + "    postLive('/_ujfe/event', {\n"
            + "      eventId: eventId,\n"
            + "      clientState: clientState()\n"
            + "    });\n"
            + "  }\n"
            + "  document.addEventListener('click', function(event) {\n"
            + "    var target = event.target.closest('[data-ujfe-event-click],[data-ujfe-event]');\n"
            + "    if (!target) { return; }\n"
            + "    event.preventDefault();\n"
            + "    postEvent(target.getAttribute('data-ujfe-event-click') || target.getAttribute('data-ujfe-event'));\n"
            + "  });\n"
            + "  document.addEventListener('change', function(event) {\n"
            + "    var target = event.target.closest('[data-ujfe-event-change]');\n"
            + "    if (!target) { return; }\n"
            + "    postEvent(target.getAttribute('data-ujfe-event-change'));\n"
            + "  });\n"
            + "  document.addEventListener('input', function(event) {\n"
            + "    var target = event.target.closest('[data-ujfe-event-input]');\n"
            + "    if (!target) { return; }\n"
            + "    postEvent(target.getAttribute('data-ujfe-event-input'));\n"
            + "  });\n"
            + "  document.addEventListener('submit', function(event) {\n"
            + "    var target = event.target.closest('[data-ujfe-event-submit]');\n"
            + "    if (!target) { return; }\n"
            + "    event.preventDefault();\n"
            + "    postEvent(target.getAttribute('data-ujfe-event-submit'));\n"
            + "  });\n"
            + "}());\n";

    private LiveClientScript() {
    }

    public static String script() {
        return SCRIPT;
    }
}
