package ujfe.live;

public final class LiveClientScript {
    private static final String SCRIPT = ""
            + "(function(){\n"
            + "  function readLocalStorage() {\n"
            + "    var values = {};\n"
            + "    try {\n"
            + "      for (var index = 0; index < window.localStorage.length; index++) {\n"
            + "        var key = window.localStorage.key(index);\n"
            + "        if (key) { values[key] = window.localStorage.getItem(key); }\n"
            + "      }\n"
            + "    } catch (error) {\n"
            + "      console.warn('UJFE could not read localStorage', error);\n"
            + "    }\n"
            + "    return values;\n"
            + "  }\n"
            + "  function clientState() {\n"
            + "    return { cookies: document.cookie || '', localStorage: readLocalStorage() };\n"
            + "  }\n"
            + "  function replaceRoot(html) {\n"
            + "    var root = document.getElementById('ujfe-root');\n"
            + "    if (root) { root.innerHTML = html; }\n"
            + "  }\n"
            + "  function replaceCss(css) {\n"
            + "    var style = document.querySelector('style[data-ujfe-css]');\n"
            + "    if (style && typeof css === 'string') { style.textContent = css; }\n"
            + "  }\n"
            + "  function applyLiveResponse(body) {\n"
            + "    try {\n"
            + "      var payload = JSON.parse(body);\n"
            + "      if (payload && typeof payload.html === 'string') {\n"
            + "        replaceCss(payload.css || '');\n"
            + "        replaceRoot(payload.html);\n"
            + "        return;\n"
            + "      }\n"
            + "    } catch (error) {\n"
            + "      // Older endpoints can still return a plain HTML fragment.\n"
            + "    }\n"
            + "    replaceRoot(body);\n"
            + "  }\n"
            + "  function getCsrfToken() {\n"
            + "    var meta = document.querySelector('meta[name=\"ujfe-csrf-token\"]');\n"
            + "    return meta ? meta.getAttribute('content') : null;\n"
            + "  }\n"
            + "  function postLive(url, payload) {\n"
            + "    var headers = { 'Content-Type': 'application/json' };\n"
            + "    var csrfToken = getCsrfToken();\n"
            + "    if (csrfToken) { headers['X-UJFE-CSRF'] = csrfToken; }\n"
            + "    return fetch(url, {\n"
            + "      method: 'POST',\n"
            + "      headers: headers,\n"
            + "      body: JSON.stringify(payload)\n"
            + "    })\n"
            + "      .then(function(response) {\n"
            + "        if (!response.ok) { throw new Error('UJFE request failed'); }\n"
            + "        return response.text();\n"
            + "      })\n"
            + "      .then(applyLiveResponse)\n"
            + "      .catch(function(error) { console.error(error); });\n"
            + "  }\n"
            + "  document.addEventListener('DOMContentLoaded', function() {\n"
            + "    postLive('/_ujfe/state', { clientState: clientState() });\n"
            + "  });\n"
            + "  function successfulControl(element) {\n"
            + "    if (!element || !element.name || element.disabled) { return false; }\n"
            + "    var tag = (element.tagName || '').toLowerCase();\n"
            + "    var type = (element.type || '').toLowerCase();\n"
            + "    if (tag === 'button' || type === 'button' || type === 'submit' || type === 'reset' || type === 'file') { return false; }\n"
            + "    if ((type === 'checkbox' || type === 'radio') && !element.checked) { return false; }\n"
            + "    return true;\n"
            + "  }\n"
            + "  function controlValue(element) {\n"
            + "    if (!element) { return ''; }\n"
            + "    var tag = (element.tagName || '').toLowerCase();\n"
            + "    var type = (element.type || '').toLowerCase();\n"
            + "    if (tag === 'select' && element.multiple) {\n"
            + "      var selected = [];\n"
            + "      for (var optionIndex = 0; optionIndex < element.options.length; optionIndex++) {\n"
            + "        var option = element.options[optionIndex];\n"
            + "        if (option.selected) { selected.push(option.value); }\n"
            + "      }\n"
            + "      return selected.join('\\n');\n"
            + "    }\n"
            + "    if (type === 'checkbox') { return element.checked ? (element.value || 'on') : ''; }\n"
            + "    if (type === 'radio') { return element.checked ? (element.value || 'on') : ''; }\n"
            + "    if (element.value == null) { return ''; }\n"
            + "    return String(element.value);\n"
            + "  }\n"
            + "  function formValue(form) {\n"
            + "    var pairs = [];\n"
            + "    var elements = form && form.elements ? form.elements : [];\n"
            + "    for (var index = 0; index < elements.length; index++) {\n"
            + "      var element = elements[index];\n"
            + "      if (!successfulControl(element)) { continue; }\n"
            + "      if ((element.tagName || '').toLowerCase() === 'select' && element.multiple) {\n"
            + "        for (var optionIndex = 0; optionIndex < element.options.length; optionIndex++) {\n"
            + "          var option = element.options[optionIndex];\n"
            + "          if (option.selected) { pairs.push(encodeURIComponent(element.name) + '=' + encodeURIComponent(option.value)); }\n"
            + "        }\n"
            + "      } else {\n"
            + "        pairs.push(encodeURIComponent(element.name) + '=' + encodeURIComponent(controlValue(element)));\n"
            + "      }\n"
            + "    }\n"
            + "    return pairs.join('&');\n"
            + "  }\n"
            + "  function eventValue(target) {\n"
            + "    if (!target) { return ''; }\n"
            + "    if ((target.tagName || '').toLowerCase() === 'form') { return formValue(target); }\n"
            + "    return controlValue(target);\n"
            + "  }\n"
            + "  function postEvent(eventId, value) {\n"
            + "    postLive('/_ujfe/event', {\n"
            + "      eventId: eventId,\n"
            + "      value: value == null ? '' : String(value),\n"
            + "      clientState: clientState()\n"
            + "    });\n"
            + "  }\n"
            + "  document.addEventListener('click', function(event) {\n"
            + "    var target = event.target.closest('[data-ujfe-event-click],[data-ujfe-event]');\n"
            + "    if (!target) { return; }\n"
            + "    event.preventDefault();\n"
            + "    postEvent(target.getAttribute('data-ujfe-event-click') || target.getAttribute('data-ujfe-event'), eventValue(target));\n"
            + "  });\n"
            + "  document.addEventListener('change', function(event) {\n"
            + "    var target = event.target.closest('[data-ujfe-event-change]');\n"
            + "    if (!target) { return; }\n"
            + "    postEvent(target.getAttribute('data-ujfe-event-change'), eventValue(target));\n"
            + "  });\n"
            + "  document.addEventListener('input', function(event) {\n"
            + "    var target = event.target.closest('[data-ujfe-event-input]');\n"
            + "    if (!target) { return; }\n"
            + "    postEvent(target.getAttribute('data-ujfe-event-input'), eventValue(target));\n"
            + "  });\n"
            + "  document.addEventListener('submit', function(event) {\n"
            + "    var target = event.target.closest('[data-ujfe-event-submit]');\n"
            + "    if (!target) { return; }\n"
            + "    event.preventDefault();\n"
            + "    postEvent(target.getAttribute('data-ujfe-event-submit'), formValue(target));\n"
            + "  });\n"
            + "}());\n";

    private LiveClientScript() {
    }

    public static String script() {
        return SCRIPT;
    }
}
