package ujfe.live;

public final class LiveDevToolsScript {
    private static final String SCRIPT = "(function(){\n"
        + "  var selected = null;\n"
        + "  var devClasses = {};\n"
        + "  var panel = null;\n"
        + "  var dismissedForCurrentActivation = false;\n"
        + "  function previewEnabled() {\n"
        + "    return !!document.querySelector('#ujfe-root [data-ujfe-dev-preview=\"true\"]');\n"
        + "  }\n"
        + "  function createPanel() {\n"
        + "    if (dismissedForCurrentActivation) { return null; }\n"
        + "    if (panel && document.body.contains(panel)) { return panel; }\n"
        + "    panel = document.createElement('div');\n"
        + "    panel.id = 'ujfe-devtools';\n"
        + "    panel.style.cssText = 'position:fixed;right:16px;bottom:16px;z-index:2147483647;"
        + "width:320px;background:#0f172a;color:#e2e8f0;border:1px solid #334155;"
        + "border-radius:8px;box-shadow:0 16px 40px rgba(15,23,42,.35);"
        + "font:12px ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;';\n"
        + "    panel.innerHTML = ''\n"
        + "      + '<div style=\"display:flex;align-items:center;justify-content:space-between;padding:10px 12px;border-bottom:1px solid #334155;\">'\n"
        + "      + '<strong>UJFE Dev Preview</strong><button data-close style=\"background:#1e293b;color:#e2e8f0;border:0;border-radius:4px;padding:4px 8px;cursor:pointer;\">x</button></div>'\n"
        + "      + '<div style=\"padding:12px;display:flex;flex-direction:column;gap:8px;\">'\n"
        + "      + '<div data-target>Nenhum elemento selecionado</div>'\n"
        + "      + '<label style=\"display:flex;flex-direction:column;gap:4px;\">classes CSS<input data-class style=\"width:100%;box-sizing:border-box;background:#020617;color:#e2e8f0;border:1px solid #475569;border-radius:4px;padding:6px;\" /></label>'\n"
        + "      + '<div style=\"display:flex;gap:8px;\"><button data-outline style=\"flex:1;background:#2563eb;color:white;border:0;border-radius:4px;padding:6px;cursor:pointer;\">Outlines</button>'\n"
        + "      + '<button data-clear style=\"flex:1;background:#475569;color:white;border:0;border-radius:4px;padding:6px;cursor:pointer;\">Limpar selecao</button></div>'\n"
        + "      + '<small style=\"color:#94a3b8;line-height:1.4;\">Clique em um elemento para editar classes no browser. Nada e persistido no Java.</small>'\n"
        + "      + '</div>';\n"
        + "    document.body.appendChild(panel);\n"
        + "    return panel;\n"
        + "  }\n"
        + "  function removePanel() {\n"
        + "    if (selected) {\n"
        + "      selected.style.outline = selected.getAttribute('data-ujfe-dev-outline') || '';\n"
        + "      selected.removeAttribute('data-ujfe-dev-outline');\n"
        + "      selected = null;\n"
        + "    }\n"
        + "    document.body.classList.remove('ujfe-dev-outlines');\n"
        + "    if (panel) { panel.remove(); panel = null; }\n"
        + "  }\n"
        + "  function describe(element) {\n"
        + "    if (!element) { return 'Nenhum elemento selecionado'; }\n"
        + "    return '<' + element.tagName.toLowerCase() + (element.id ? '#' + element.id : '') + '>';\n"
        + "  }\n"
        + "  function selectElement(element, panel) {\n"
        + "    if (!panel) { return; }\n"
        + "    if (selected) { selected.style.outline = selected.getAttribute('data-ujfe-dev-outline') || ''; selected.removeAttribute('data-ujfe-dev-outline'); }\n"
        + "    selected = element;\n"
        + "    if (selected) {\n"
        + "      selected.setAttribute('data-ujfe-dev-outline', selected.style.outline || '');\n"
        + "      selected.style.outline = '2px solid #38bdf8';\n"
        + "    }\n"
        + "    panel.querySelector('[data-target]').textContent = describe(selected);\n"
        + "    panel.querySelector('[data-class]').value = selected ? selected.getAttribute('class') || '' : '';\n"
        + "    applyClassCss(selected ? selected.getAttribute('class') || '' : '');\n"
        + "  }\n"
        + "  function rememberClasses(classValue) {\n"
        + "    String(classValue || '').split(/\\s+/).forEach(function(className) {\n"
        + "      if (className) { devClasses[className] = true; }\n"
        + "    });\n"
        + "  }\n"
        + "  function classQuery() {\n"
        + "    return Object.keys(devClasses).join(' ');\n"
        + "  }\n"
        + "  function devStyleElement() {\n"
        + "    var style = document.querySelector('style[data-ujfe-dev-css]');\n"
        + "    if (!style) {\n"
        + "      style = document.createElement('style');\n"
        + "      style.setAttribute('data-ujfe-dev-css', '');\n"
        + "      document.head.appendChild(style);\n"
        + "    }\n"
        + "    return style;\n"
        + "  }\n"
        + "  function applyClassCss(classValue) {\n"
        + "    rememberClasses(classValue);\n"
        + "    var query = classQuery();\n"
        + "    if (!query) { return; }\n"
        + "    fetch('/_ujfe/css?classes=' + encodeURIComponent(query))\n"
        + "      .then(function(response) { if (!response.ok) { throw new Error('UJFE CSS request failed'); } return response.text(); })\n"
        + "      .then(function(css) { devStyleElement().textContent = css; })\n"
        + "      .catch(function(error) { console.error(error); });\n"
        + "  }\n"
        + "  function bindPanel(panel) {\n"
        + "    if (!panel || panel.getAttribute('data-bound')) { return; }\n"
        + "    panel.setAttribute('data-bound', 'true');\n"
        + "    panel.querySelector('[data-close]').addEventListener('click', function(){ dismissedForCurrentActivation = true; removePanel(); });\n"
        + "    panel.querySelector('[data-clear]').addEventListener('click', function(){ selectElement(null, panel); });\n"
        + "    panel.querySelector('[data-outline]').addEventListener('click', function(){ document.body.classList.toggle('ujfe-dev-outlines'); });\n"
        + "    panel.querySelector('[data-class]').addEventListener('input', function(event){ if (selected) { selected.setAttribute('class', event.target.value); applyClassCss(event.target.value); } });\n"
        + "  }\n"
        + "  function ensureStyle() {\n"
        + "    if (document.querySelector('style[data-ujfe-dev-outline-css]')) { return; }\n"
        + "    var style = document.createElement('style');\n"
        + "    style.setAttribute('data-ujfe-dev-outline-css', '');\n"
        + "    style.textContent = '.ujfe-dev-outlines #ujfe-root *{outline:1px dashed rgba(37,99,235,.45);outline-offset:-1px;}';\n"
        + "    document.head.appendChild(style);\n"
        + "  }\n"
        + "  function sync() {\n"
        + "    if (!previewEnabled()) {\n"
        + "      dismissedForCurrentActivation = false;\n"
        + "      removePanel();\n"
        + "      return;\n"
        + "    }\n"
        + "    ensureStyle();\n"
        + "    bindPanel(createPanel());\n"
        + "  }\n"
        + "  function boot() {\n"
        + "    sync();\n"
        + "    document.addEventListener('click', function(event) {\n"
        + "      var panelElement = document.getElementById('ujfe-devtools');\n"
        + "      if (!panelElement || panelElement.contains(event.target)) { return; }\n"
        + "      if (event.target.closest('[data-ujfe-dev-control]')) { return; }\n"
        + "      var root = document.getElementById('ujfe-root');\n"
        + "      if (!root || !root.contains(event.target)) { return; }\n"
        + "      event.preventDefault();\n"
        + "      event.stopPropagation();\n"
        + "      selectElement(event.target, panelElement);\n"
        + "    }, true);\n"
        + "    var root = document.getElementById('ujfe-root');\n"
        + "    if (root) {\n"
        + "      new MutationObserver(sync).observe(root, { childList: true, subtree: true, attributes: true });\n"
        + "    }\n"
        + "  }\n"
        + "  if (document.readyState === 'loading') { document.addEventListener('DOMContentLoaded', boot); } else { boot(); }\n"
        + "}());\n";

    private LiveDevToolsScript() {
    }

    public static String script() {
        return SCRIPT;
    }
}
