ujfe.live.title=UJFE Servlet Tomcat Example
ujfe.live.lang=en
ujfe.live.dev-tools-enabled=true
ujfe.live.css-mode=internal
ujfe.live.max-json-payload-bytes=1048576
ujfe.client-state.cookies=ujfe_demo
ujfe.client-state.local-storage-keys=ujfe.theme
ujfe.client-state.session-storage-keys=ujfe.tab
